### ISSUE TITLE
Completed homework

### ISSUE THREAD

**Issue by tklecka** [htl-perg-2019-20-5bhif/highscore-exercise-tklecka#2]
Dear Mr. Stropek!
@tbrych, @markuskurzmann and I implemented the new homework in this GitHub-Repo: https://github.com/tklecka/highscore-exercise-tklecka  
We completed every extra challange including CI/CD

We wont merge the Fork because the GitHub Action Secrets will not be merged and the Build will fail.
  
Game: https://highscore-exercise-tklecka.azurewebsites.net/   
API: https://highscore-exercise-tklecka-api.azurewebsites.net/api/highscore

**Comment by rstropek** [comment]
Wow, very well done! The game works and the code looks good 👍. Congrats for this great work!
